---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gazpar2haws
  namespace: home-assistant
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-reader
    kind: ClusterSecretStore
  target:
    name: gazpar2haws
    creationPolicy: Owner
  data:
    - secretKey: GRDF_USERNAME
      remoteRef:
        key: gazpar2haws
        property: grdf-username
    - secretKey: GRDF_PASSWORD
      remoteRef:
        key: gazpar2haws
        property: grdf-password
    - secretKey: GRDF_PCE_IDENTIFIER
      remoteRef:
        key: gazpar2haws
        property: grdf-pce-identifier
    - secretKey: HOMEASSISTANT_TOKEN
      remoteRef:
        key: gazpar2haws
        property: ha-token
