---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - matter-server-pvc.yaml
  - matter-server-deployment.yaml
  - external-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - gazpar2haws-secret.yaml
  - gazpar2haws-deployment.yaml
