---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-config
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: media-config
    namespace: media
  nfs:
    server: 172.20.2.150
    path: /var/nfs/shared/Servers/media/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: media-config
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: media-data
    namespace: media
  nfs:
    server: 172.20.2.150
    path: /var/nfs/shared/Servers/media/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  volumeName: media-data
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: media-library
    namespace: media
  nfs:
    server: 172.20.2.150
    path: /var/nfs/shared/Partagé/Bibliotheque
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  volumeName: media-library
  storageClassName: ""
