---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          image: ghcr.io/hotio/bazarr:latest
          ports:
            - containerPort: 6767
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Europe/Paris"
          readinessProbe:
            httpGet:
              path: /
              port: 6767
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: bazarr
            - name: data
              mountPath: /data/movies
              subPath: movies
            - name: data
              mountPath: /data/tv
              subPath: tv
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: media-config
        - name: data
          persistentVolumeClaim:
            claimName: media-data
