---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources/metallb.yaml
  - metallb-operator.yaml
  - metallb-config.yaml
  - sources/traefik.yaml
  - traefik-operator.yaml
  - traefik-config.yaml
