---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: ghcr.io/hotio/radarr:latest
          ports:
            - containerPort: 7878
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Europe/Paris"
          readinessProbe:
            httpGet:
              path: /
              port: 7878
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: radarr
            - name: data
              mountPath: /data/downloads
              subPath: downloads
            - name: data
              mountPath: /data/movies
              subPath: movies
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: media-config
        - name: data
          persistentVolumeClaim:
            claimName: media-data
