---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ct-stream-data
  namespace: fugue
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
