---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: timescaledb-credentials
  namespace: database
spec:
  refreshInterval: 0
  target:
    name: timescaledb-credentials
    creationPolicy: Owner
    template:
      data:
        username: homeassistant
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: timescaledb-password
