apiVersion: ENC[AES256_GCM,data:DWA=,iv:EhiBUiv/1bpEco3JXtitZW6Uw7OHHwacIv5Hk81FmU4=,tag:TRiBiw6dP5/UDfBc7CbQHQ==,type:str]
kind: ENC[AES256_GCM,data:+TkK5Pos,iv:X/ACjFUCnf9h3OGGjqLE9zH6zYaNGCiQCGm7wO+1CAc=,tag:5/aQMo8rhl1yCm0DVozZVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oynIlW7vNOgfeRY=,iv:8K1VO1xkqvm25sb3QEaEJWQ80LpGCZpb2d7LZxc/WUs=,tag:+tEC+EnRYkTCZ6Zww+lcuQ==,type:str]
    namespace: ENC[AES256_GCM,data:WLCD2lUV5lg=,iv:8x6KKC74atHlTVPrKW5mdPdTxm389ohTfIpjMY11j9g=,tag:FTrw9fglbAkdfYk9+itu9g==,type:str]
type: ENC[AES256_GCM,data:U0IGpYsX,iv:nmgduqt6azJIUwqfSwUziCRjZmj8FXc0AuQNcnv6KsQ=,tag:Bp0UbOtjsTrp2wAMpi5OcQ==,type:str]
stringData:
    grdf-username: ENC[AES256_GCM,data:KoG6hBJ3bnIa827PnEm9LrV9bUvFFhEWgu8=,iv:litTGt1SL6hPMjsT+3dcJfmuoocsPD28JwfPkr/pW3A=,tag:Z851XoL1MviRfKAJoeTozA==,type:str]
    grdf-password: ENC[AES256_GCM,data:MpHZHBBL8zXOlg1gAebEm1ZJdMpHrg==,iv:U1RkjsPUgE1TYlJM2jqUqIkTqCM4nBn012R/BQOxOck=,tag:8/6yySwpkwGvKELjI+EEyg==,type:str]
    grdf-pce-identifier: ENC[AES256_GCM,data:u7/RwyYurxu4Gv6x+Ss=,iv:l7NszyetLpd0O6e2jIG2NjOmgdLCrAxqp20OcTO5y5A=,tag:Gm9PHY4mY2S4P6sP0vD4fA==,type:int]
    ha-token: ENC[AES256_GCM,data:EUSsoGtby08lC2TArf1yJw7H29j04Wi7GsAa8j/9Zk5bGpXhFz1d+5kM3/7HdbTn5VlCHd6SRs8WQ8ikqNTAjsTooORyKBebnOyGDocPVKTOBeCaO7AyXjVmjIgNZALjOYJoM0noh0JPC/cMgFMAZzatcPNCT9Ww6TdDmHCN9QOqNS7Es96kLsClbGsqA0CJirBw+o5tfpTNQSiiKTaDcOtBsOLjRXoYqj0gnVUiLIXrL5VfEyT+,iv:3hGyO80Q+SCtIh9Qir8G6dwoBC0m4fZcoZhHwm69jAY=,tag:RGTUsx27Ni/2UUUCgwAoyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeUQ5WXdwZXh1Ny95Wmpr
            SjB1dU92eWNzSmN3eHVKUjRiTENZSkxnMldRClQ0OG9JSW9EQjgxOFdxK2ZIek5I
            dndJcUdOSEcrZDlKbUV1TmcyaWdadk0KLS0tIGUyUTVZK2J4YU84RmNYeFVzWjNL
            N1dFUTUxT0NjN0YzU0xuUDU0VXFoL2MKi51tCS6COL5U+Y/gHreFpaHzJBUgyjGD
            Ca/QW+9qO29dx0XiAf2pgEW51kQmQ2YMyZCYKNicBkPEWbOsF3GNNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1serescfzmafna2ep2c5k23s9qr2gajm80wuhdt92mj5q7zedhgpsqsradh
    lastmodified: "2026-08-13T12:11:16Z"
    mac: ENC[AES256_GCM,data:CmwXxQml0mLVOmSaae/YBVx7umAsoghiDH32S56zCJTaA+YRvTmQiGy4RqIMoWFMVXj0gH1/1rpRr7Ubjo9/MBM8ZTEFj60C6w51o31yc3e9XRH6V68IARjiRVyghbB8bnzm9swIgykybm8n2i8cLFNuWsGAzS1ztytN6o4v4qk=,iv:xwYRhkh/moK7+z5u4NCpZ+arI0BkND+Ekw0JQosy6bQ=,tag:6OWTjr9k/HBaafkVkFhLaQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
