apiVersion: ENC[AES256_GCM,data:El8=,iv:lLcwojXtIvk/QxE4z+e6Mz5cMg0/OIrmOIINUDV7L/s=,tag:RqA3SuQaGdYV8eWckuq/5w==,type:str]
kind: ENC[AES256_GCM,data:p0GsD/DI,iv:hjMb7g7ELWAUiQZXZuFB/rZRUldDLcpd+oxIuDHuoBE=,tag:KHwF98jNtsWLOrIKcBhnyw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:trt98qWk/wqzylY=,iv:trkqBoAg/O15kyZcNiQ6WObBq9ELMM7rKOuT/9CkV6U=,tag:0eeXtKAXCzoxxcPaahnMTg==,type:str]
    namespace: ENC[AES256_GCM,data:TBBuVQtqKLw=,iv:tzyJjwLZKucLHRo4mcUyTTMbXol1eOFClOEJAznHbt8=,tag:t2iG1QoC8cLWZFupmfocXw==,type:str]
type: ENC[AES256_GCM,data:AIcOwiMN,iv:DWt7Ynf8KncF3t4Mv9zte8P8ll0HnKXt8m2a7gZnwyw=,tag:JTRmjv04DPl5IMHPUd5UJg==,type:str]
stringData:
    grdf-username: ENC[AES256_GCM,data:d5K0x59lLubb6mtjBkwhVjInyuKb9yY+mB0=,iv:QliE7hqpMZtLNEEIUM4V4W2G4+JPuADkwpsEdL2d4Kw=,tag:mrqqG0GdcPnRDXjJf6/dww==,type:str]
    grdf-password: ENC[AES256_GCM,data:AYeqxtrCyg3LCxaXJXRFKfc3nRiceA==,iv:ig8uYNfP0q8pOjbN3tvVM2BR2rJvtTpeKtGhnbGGGk0=,tag:WeoDF6KAWj/WDNeSCqTgsA==,type:str]
    grdf-pce-identifier: ENC[AES256_GCM,data:fIJ50YTWmI3msmTV7Co=,iv:afUNYrFL9dyr0AYshVh3+ZI2IxOKTVfDdzEcr2IgRyE=,tag:Czws06tg1b/tvA2Q92nioA==,type:str]
    ha-token: ENC[AES256_GCM,data://a6h+q9H4OGvxejM9rLpuQvh1QraL05HyI8BmaMpk81iNmYawWyMdaQjOVlx+m+te3a175FzKEQuAK+GT6m3M7MjMw+yPqHrNBZngoqLe2aWPtebF34evZG+mWojMpPiqP8xFq856ekyxFO/KZ1725ySY9By5V3uTR1MemhHqkmfm9bXb9EOMAl+RaaiqyHIwcjOh36cRFI+tV9ixbQzJQXrZ5T21apuKwW8ahYp9U4hFj/irwp,iv:aabG3Q0btf6YK7pDLBdGCBza1PwiMYo3s4KARbcTwMU=,tag:dDtA177hQwjAoLMaEBjs5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdW1ZZUFNZGFvTTFlUU13
            RWM2MzIrbURtZFpiQUJpcTVHTGFzM01sNWg0CjJDS0xyOU9qVHBXallZbklMYTU1
            YWk2RFV0VTJUSDdkTndUeHhUVHVvZGcKLS0tIEZMeGl3VzZxUFNaeTRMOEdHYUEy
            Q1VDT2k3aFpxYlNoZFpZU2IyZGo0Y3cK6Sag1gZ05hBSK8WMhZeOqDkVEiV2GDda
            Pep99eGvK/C8GN+mCK9gLsh2zQh1D7Ky3BhRdpHS/25IZnHz0BnoEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1serescfzmafna2ep2c5k23s9qr2gajm80wuhdt92mj5q7zedhgpsqsradh
    lastmodified: "2026-08-20T11:50:40Z"
    mac: ENC[AES256_GCM,data:w0N09gMlenZkJSX2N0eWgwv+ZcTkPMaoUwMj/4+F0Du3VhqBX3ap0MwFQT6MkBUNQMYGYuhRHbNqlWhh0sUNmkDy7nVb94JvEu6md7v8htlynroN6g14JkQS5Zyl5swqezOmRQoBVx0t8UAr1b1Y/sSWLRUvJDH0afX9PPBxl1Y=,iv:5VBw1t9EaGD4f47NIc5nmr5cCnZRFEOvnfnBWhOUhnU=,tag:Tb5y5Mk+rdhIhPS4Ymnr4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
