---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: timescaledb-password
  namespace: database
spec:
  length: 32
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: jellyfin-db-password
  namespace: database
spec:
  length: 32
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: prismedia-db-password
  namespace: database
spec:
  length: 32
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
