---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
        - name: lidarr
          image: ghcr.io/hotio/lidarr:latest
          ports:
            - containerPort: 8686
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Europe/Paris"
          readinessProbe:
            httpGet:
              path: /
              port: 8686
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: lidarr
            - name: data
              mountPath: /data/downloads
              subPath: downloads
            - name: data
              mountPath: /data/music
              subPath: music
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: media-config
        - name: data
          persistentVolumeClaim:
            claimName: media-data
