---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prismedia-db-credentials
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-reader
    kind: ClusterSecretStore
  target:
    name: prismedia-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: prismedia-db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: prismedia-db-credentials
        property: password
