apiVersion: ENC[AES256_GCM,data:SNc=,iv:Yp/5nIOlXhNNJJaj5Gc9TNxXCQvw/2UDIrK0NWoq6GQ=,tag:FNwBA2x+7QBfFR/JHjwN7Q==,type:str]
kind: ENC[AES256_GCM,data:t16OugNF,iv:OWMeQpjmJD0PVzozeghJ5aDCqAyskl1sGstrOMAMY1I=,tag:xNu45KS4dIiJYjxrlQUeSA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bBeFH878RS+f,iv:s8Ldv7/YuTSqUZH4pS58fc5EBr8VG9Z9XZaEc2JckTU=,tag:CvznL8XcUaKJJNA8qgJcRA==,type:str]
    namespace: ENC[AES256_GCM,data:OcgKHJQ=,iv:oGZgcVOP6r5MSa3dD7lBlOmtzz1VmXXtdbJHUGxcz7w=,tag:IqzPBAZqxvm0x8UWtFrTVA==,type:str]
type: ENC[AES256_GCM,data:vjVFixxm,iv:ZrAjTS2B+uUjhKtPtRxvS1Uoi/2ZeP3FoVsjM/tXWEg=,tag:eCv8VYZqOaX0FkgtsJk0VA==,type:str]
stringData:
    PRISMEDIA_SECRET: ENC[AES256_GCM,data:P7jZEKNTuJUAaqWyUQ9OH7KTes6TgXK9tpI2GbbPs8aowGJt/OA6Ga1vbeRM3sXE,iv:BftJw+C4Hk/c1r+zOYfOesVw2g6H6VksDOggo5MtXiI=,tag:qigSB6Ar/5XocqW/xbo9GQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESmMwQ2lSSXdoSjU1K3FF
            NXpVbFN4NWFxR29ucE5EQk5ublczaVdoeUFBCmV1WEd2OStRVGJzYlZxMlZqK3o5
            UCsxdjFlZnZyTHJLVUNBS2xxL09HbkkKLS0tIFdxc01ETk5iWjhmc2h5aTNTNVBM
            bTlCNG96QzJBMlZsQ2RUTDhGMFdmUm8KE/AtIemlN0/JBkVPgWt68I/rNRgmb8QR
            YZWnJ6r/PmXFtnrLHxoswcEUqvVQLE4Jn+citi5+rMEwQn6ZmiVRZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1serescfzmafna2ep2c5k23s9qr2gajm80wuhdt92mj5q7zedhgpsqsradh
    lastmodified: "2026-08-09T09:09:21Z"
    mac: ENC[AES256_GCM,data:/VZVHqHKyqfnoL1pgGbG+LzoXpd0QaW/8hgxHPYWKqo3afu8uBLHDmYfjOezZWRbrjHj8pBxVi9obM0gJuwXm6Z0q5UXf+WrRRObacyOsF13KwMUm2gtW86G31g63W9dqgDM1mpsxGD0bPwUNvO8BlzahGSVfgE/zX0RU/CtYpU=,iv:bt0akXCNXv7nUVoWfk0jZ8vA1mIsIc0mv70XorTxNZI=,tag:1B3YxVbCI7mdPaJy610Ldg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
