apiVersion: ENC[AES256_GCM,data:PCw=,iv:pjQdKnUO+Y0f32T8kQnVOl9WGQnGaoitazCbcJ7+yHQ=,tag:Afckcrhs8ET3tjEej60/5g==,type:str]
kind: ENC[AES256_GCM,data:kLSFKh2g,iv:acwDjuFXHoGUT4TBQpJlaSUviWTKsTB6LikwP0wiFuU=,tag:GTx8QcoNFZVZsAUOL++y2A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NnaS0w==,iv:GSTOiOGTN2J5rAmngQsdf2lb/ZJ49izNFdsFj2dUAZY=,tag:BPv5CCm9WCMduPGAu6GK4w==,type:str]
    namespace: ENC[AES256_GCM,data:py++0xo=,iv:ERb1FFbKDwkibqAebyIrALNFJVQAppRpqnRdyU7AQg4=,tag:Nu4uL0RQ1ui56apu6D1CHA==,type:str]
type: ENC[AES256_GCM,data:mLccH/oG,iv:3IdlxoLU5ffKzVUxWYqawuhjCn2IxYu0CdLAOj+3/sY=,tag:ByTOnBiV5A8Q5Qc6aG4rhQ==,type:str]
stringData:
    PLEX_CLAIM_TOKEN: ENC[AES256_GCM,data:m6QXtNLDFoLjyQ4EkiAggtmhwVPmtsN+NS8=,iv:KgH3brYiJg1Ut5foJFk2jQMqGyK+IGhmRIAQwKMyY08=,tag:8EBK1Warc45K4uEl1vAETQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbFBkYy96aW9pN0h2OXF6
            d2lnMi9qUVV1cG90MFRpeTQxRFVCeXkyY0FVCnpvU1lPTEZrYVB4eFNSdGx6ZWpx
            VnFoU2t5VzIvU2hrdWw0Umw2TlJub0UKLS0tIHN4UFFCTVNFR3NJS1VIQ1JFSEpy
            d1NsTTZZa3ZnUjUzejk5WDduTnVSbmsKZKNTSkVhFz5LMIT7MBIYaxe8aS+xHAcb
            eadmfrh4mmiL7+b2qyCi0HJFU6hk9hk53idFVhWxM6Cplb0Wc0F4sA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1serescfzmafna2ep2c5k23s9qr2gajm80wuhdt92mj5q7zedhgpsqsradh
    lastmodified: "2026-08-07T20:38:36Z"
    mac: ENC[AES256_GCM,data:vLET/YJbLBvkImZf04SJO+6YCHrD/zwsXMeNjkvfoyLH1J2ch8kW4bW6kGRvgzQyiKHLqAjYhgPQqGmALCeXjSYYpk8Xinu8idtRpzCVPodQo4V6bGb/sVifwZzScTYB4jXfN2+VRWFZKcyYFOEpVQi4NVPDkTUsgtPCsqODcNs=,iv:JdtOQ9ZTcTUlLu3OkjXOc/7EgRVrePl22JRIrkebV9Q=,tag:7/ApE/5Vx4RziA2r9UyULg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
