---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lazylibrarian
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lazylibrarian
  template:
    metadata:
      labels:
        app: lazylibrarian
    spec:
      containers:
        - name: lazylibrarian
          image: ghcr.io/hotio/lazylibrarian:latest
          ports:
            - containerPort: 5299
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Europe/Paris"
          readinessProbe:
            httpGet:
              path: /
              port: 5299
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: lazylibrarian
            - name: data
              mountPath: /data/downloads
              subPath: downloads
            - name: data
              mountPath: /data/books
              subPath: books
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: media-config
        - name: data
          persistentVolumeClaim:
            claimName: media-data
